version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=password
      - ORACLE_DATABASE=tasksdb
      - APP_USER=filab
      - APP_USER_PASSWORD=passwrd
    ports:
      - "1521:1521"
    volumes:
      - ./sql:/container-entrypoint-initdb.d
# volumes:
#   oracle-data:
